[project]
name = "fastapi-setup"
version = "0.1.0"
description = "this is a fastapi setup to learn how to use fastapi, and be comfortable with it."
readme = "README.md"
authors = [
    { name = "Deelolade", email = "oluwanisholahabeeb13@icloud.com" }
]
requires-python = ">=3.10"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi[standard]>=0.142.2",
    "greenlet>=3.5.6",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
fastapi-setup = "fastapi_setup:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
